[tool.black]
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | pyproject.toml
)/
'''

[tool.flake8]
ignore = ["E203", "E266", "E501", "W503", "F403", "F401"]
max-line-length = 89
max-complexity = 18
select = ["B", "C", "E", "F", "W", "T4", "B9"]


[tool.isort]
profile = "black"

